python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/1.가로형간판/가로형간판1" "[원천]Training_간판_가로형간판_원천데이터1"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/1.가로형간판/가로형간판2" "[원천]Training_간판_가로형간판_원천데이터2"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/1.가로형간판/가로형간판3" "[원천]Training_간판_가로형간판_원천데이터3"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/1.가로형간판/가로형간판4" "[원천]Training_간판_가로형간판_원천데이터4"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/1.가로형간판/가로형간판5" "[원천]Training_간판_가로형간판_원천데이터5"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/2.돌출간판/돌출간판1" "[원천]Training_간판_돌출간판_원천데이터1"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/2.돌출간판/돌출간판2" "[원천]Training_간판_돌출간판_원천데이터2"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/3.세로형간판" "[원천]Training_간판_세로형간판_원천데이터"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/4.실내간판/실내간판1" "[원천]Training_간판_실내간판_원천데이터1"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/4.실내간판/실내간판2" "[원천]Training_간판_실내간판_원천데이터2"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/5.실내안내판/새 폴더" "[원천]Training_간판_실내안내판_원천데이터1"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/5.실내안내판/새 폴더 (2)" "[원천]Training_간판_실내안내판_원천데이터2"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/6.지주이용간판" "[원천]Training_간판_지주이용간판_원천데이터"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/7.창문이용광고물" "[원천]Training_간판_창문이용광고물_원천데이터"
python scripts/preprocess_external_dataset.py "[라벨]Training/1.간판/8.현수막" "[원천]Training_간판_현수막_원천데이터"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/01.총류" "[원천]Training_책표지1/01.총류"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/02.철학" "[원천]Training_책표지1/02.철학"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/03.종교" "[원천]Training_책표지1/03.종교"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/04.사회과학" "[원천]Training_책표지1/04.사회과학"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/05.자연과학" "[원천]Training_책표지2/05.자연과학"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/06.기술과학" "[원천]Training_책표지2/06.기술과학"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/07.예술" "[원천]Training_책표지2/07.예술"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/08.언어" "[원천]Training_책표지2/08.언어"
python scripts/preprocess_external_ dataset.py "[라벨]Training/2.책표지/09.문학" "[원천]Training_책표지3/09.문학"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/10.역사" "[원천]Training_책표지3/10.역사"
python scripts/preprocess_external_dataset.py "[라벨]Training/2.책표지/11.기타" "[원천]Training_책표지3/11.기타"

python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/1.가로형간판" "[원천]Validation_간판1/01.가로형간판"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/2.돌출간판" "[원천]Validation_간판2/02.돌출간판"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/3.세로형간판" "[원천]Validation_간판2/03.세로형간판"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/4.실내간판" "[원천]Validation_간판2/04.실내간판"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/5.실내안내판" "[원천]Validation_간판2/05.실내안내판"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/6.지주이용간판" "[원천]Validation_간판3/06.지주이용간판"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/7.창문이용광고물" "[원천]Validation_간판3/07.창문이용광고물"
python scripts/preprocess_external_dataset.py "[라벨]Validation/1.간판/8.현수막" "[원천]Validation_간판3/08.현수막"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/01.총류" "[원천]Validation_책표지/01.총류"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/02.철학" "[원천]Validation_책표지/02.철학"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/03.종교" "[원천]Validation_책표지/03.종교"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/04.사회과학" "[원천]Validation_책표지/04.사회과학"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/05.자연과학" "[원천]Validation_책표지/05.자연과학"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/06.기술과학" "[원천]Validation_책표지/06.기술과학"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/07.예술" "[원천]Validation_책표지/07.예술"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/08.언어" "[원천]Validation_책표지/08.언어"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/09.문학" "[원천]Validation_책표지/09.문학"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/10.역사" "[원천]Validation_책표지/10.역사"
python scripts/preprocess_external_dataset.py "[라벨]Validation/2.책표지/11.기타" "[원천]Validation_책표지/11.기타"